#服务配置
server:
  port: 9001
#spring配置
spring:
  #1.应用配置
  application:
    name: jasper-springboot #指定服务名
  #2.数据库连接池
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ihrm?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root1234
  #3.JPA
  jpa:
    database: MySQL
    show-sql: true
    open-in-view: true
    hibernate:
      #jpa 自动建表
      ddl-auto: update
    #Spring boot2.0之前使用的是InnoDB，Spring boot2.0之后默认使用的是myisam引擎，如果数据库用的是InnoDB，
    #那么在2.0之后的spring boot+jpa自动建表时就会出错
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
